# CW9: Gas, Pressure and Mean-free-path

## Objective

In Chapter S1 of Matter & Interactions 4e, you have learned about the ideal gas and Maxwell distribution of velocities of the gas molecules. In this activity we will simulate a gas system consisted 50 He atoms in a box of side length $L$ at temperature $T$. Your mission is to find the pressure, and the mean free path between collisions of the atoms. 


Reference: [Jupyter VPython Documentation](http://www.glowscript.org/docs/VPythonDocs/index.html)



## Numpy arrays

In this homework, we will  use data structure and commands from the Numerical Python (numpy) package for efficiency. Vpython is built on top of numpy so no further explicit import is necessary. You can find numpy documentations at http://devdocs.io/numpy~1.13/ .

The main object in numpy is the numpy array, which is a (usually fixed-size) multidimensional container of items of the same type and size. The number of dimensions and items in an array is defined by its `shape`, which is a tuple of $N$ positive integers that specify the sizes of each dimension. 

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [1]:
from __future__ import division, print_function
import numpy as np
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a))            
print(a.shape)            
print(a[0], a[1], a[2])   
a[0] = 5                 
print(a)                 

b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])   


<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [2]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)             # Prints "[[ 0.  0.]
                     #          [ 0.  0.]]"
    
b = np.ones((1,2))   # Create an array of all ones
print(b)             # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7.) # Create a constant array
print(c)              # Prints "[[ 7.  7.]
                      #          [ 7.  7.]]"

d = np.eye(2)        # Create a 2x2 identity matrix
print(d)             # Prints "[[ 1.  0.]
                     #          [ 0.  1.]]"
    
e = np.random.random((2,2)) # Create an array filled with random values
print(e)                    # Might print "[[ 0.91940167  0.08143941]
                            #               [ 0.68744134  0.87236687]]"


[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 7.  7.]
 [ 7.  7.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.92844286  0.69483696]
 [ 0.13336135  0.04884073]]


Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:


In [10]:
from __future__ import division, print_function
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


To compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices, use `dot`. `dot` is available both as a function in the numpy module and as an instance method of array objects:


In [8]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))


<577.541386, 777.488650, 955.268206>
<-505.867777, -9.359486, 1262.770839>
<1159.742297, 41.339169, -709.837220>
<-258.817431, 998.154862, 887.288233>
<-380.190695, 1306.139051, -5.984429>
<91.206994, 819.346992, -1082.096018>
<-227.012470, 981.039681, -914.661950>
<526.143050, 338.495322, -1207.962917>
<-3.481739, -199.929582, -1345.583903>
<952.380653, 764.390015, -599.382181>
<152.212867, -110.325667, 1347.308239>
<446.483469, -1185.490814, 495.826624>
<-901.097615, 468.224817, -905.189820>
<533.614331, 388.858609, -1189.379976>
<5.739140, -607.340015, 1217.244909>
<-1101.781301, -291.847384, -742.619061>
<404.848297, 710.344824, 1087.238745>
<394.469003, -658.710944, -1122.975555>
<346.401836, -734.570353, 1091.325875>
<-304.601565, -1177.818806, 608.720582>
<-934.863727, -100.474923, 983.114745>
<-1064.609157, -579.430937, -617.614064>
<-122.482178, 56.123258, 1353.672152>
<334.513606, -1303.876362, 196.435946>
<-426.771204, -111.214765, -1286.886792>
<-1279.554812, -384.382835, 2

## Handle collisions between atoms

In this simulation, one important aspect is to handle collisions between atoms. 

Here is an efficient  code snippet that can be used to detect the collisions, where `pos` is a numpy array of size   of $N\times 3$ which contains the positions of the atoms after the update, and `radius` is an $N\times 1$ numpy array which stores the radii of the atoms,

In [ ]:
r = pos-pos[:,np.newaxis] # all pairs of atom-to-atom vectors
rmag = sqrt(sum(square(r),-1)) # atom-to-atom scalar distances    
hit = less_equal(rmag,radius+radius[:,newaxis])-identity(N)
hitlist = sort(nonzero(hit.flat)[0]).tolist() # i,j encoded as i*N+j

The first line generates an $N\times N$ matrix of inter-atomic vectors between atom $i$ and $j$ (`r` is an $N\times N \times 3$  numpy array).
The second line generates an $N\times N$ matrix of the inter-atomic distances. 
The third line uses a numpy function `less\_equal` to determine if a collision occurs. `hit` is    an $N\times N$ matrix where `hit[i,j]` indicates  if a collision occurred between atom $i$ and $j$. The fourth line find the indices of  nonzero elements in `hit` by flattening it to a 1d array first. The flattening stores the element `hit[i,j]` to the element `i*N+j` 

You will loop through `hitlist` to handle the collisions. Notice that `hitlist` stores collision between atoms $i$ and $j$ as `[i,j]` and `[j,i]`. When handling collision, you want to remove one of them first so that you don't handle the collision twice. 

If a collision is detected, you want to trace back in time to when the two atoms make contacts,  handles the bound, and move forward in time using the new velocities.

Here is a code snippet that handles the collision between two atoms. The velocities can be obtained by transforming into the center-of-mass frame, handling the bounce and transforming back to the lab frame.  


In [ ]:
def vcollision(a1,a2):
    '''
    Function to find the velocities of atoms after each collision
    '''
    v1 = a1.v - 2 * a2.m/(a1.m+a2.m) *(a1.pos-a2.pos) \
    * dot (a1.v-a2.v, a1.pos-a2.pos) / mag(a1.pos-a2.pos)**2
    v2 = a2.v - 2 * a1.m/(a1.m+a2.m) *(a2.pos-a1.pos) \ 
    * dot (a2.v-a1.v, a2.pos-a1.pos) / mag(a2.pos-a1.pos)**2
    return v1, v2


## Handle collisions between atoms and walls
The collisions between atoms and walls can be easily handled by checking if the particle hits the wall.
Here is a code snippet that handles the collisions with the walls, 

In [ ]:
outside = less_equal(pos,Ratom) # walls closest to origin
p1 = p*outside
p = p-p1+abs(p1) # force p component inward
outside = greater_equal(pos,L-Ratom) # walls farther from origin
p1 = p*outside
p = p-p1-abs(p1) # force p component inward

Using the starter code below, answer the following questions


* Find the pressure of the system.  You should find the pressure is much larger than the pressure of an ideal gas at this temperature and density. The reason is that we use larger size of atoms. You can modify the atom size to the real size of He atom of 31 pm ($31\times 10^{-12}$) and get a better result, but then the atoms rarely collide and it takes very long time to reach the equilibrium state.
* Run the simulation long enough that the gas reaches equilibrium. The speed distribution histogram approaches the theoretical Maxwell distribution. 
* Add some codes to find the mean free path of the atoms. Free path is the distance one atom travels between two consecutive collisions with other atoms (this means that the collisions of the atoms with the walls are not considered for calculating the free path). Obtain every free path of all atoms, average them, and print the mean free path every 1000*dt. Compare your mean free path to the theoretical result
$l=\frac{V}{\sqrt{2\pi d^2 N}}$, where $V$ is the volume of the container, $N$ the number of particles contained, and $d$ is the diameter of the atoms.


In [1]:
from vpython import *
from random import random 
import numpy as np

#initialize the variable
N = 50 
L = ((24.4E-3/(6E23))*N)**(1/3.0)/2 
m, size = 4E-3/6E23, 310E-12 
L_size=L-size  
k, T = 1.38E-23, 298.0 
t, dt = 0., 0.5E-13 
vrms = (3*k*T/m)**0.5 
deltav = 100.
dv=10.
pavg = sqrt(2*m*1.5*k*T)

#prepare to plot
scene1=canvas(width=400,height=400,align='left') 
g=graph(x=800, y=0, ymax = N*deltav/1000.,width=500, height=300, xtitle='v', ytitle='dN',align='left') 
theory = gcurve(graph=g,color=color.cyan) 
for v in arange(0.,3001.+dv,dv):
    theory.plot(pos=(v,(deltav/dv)*N*4.*pi*((m/(2.*pi*k*T))**1.5)*exp((-0.5*m*v**2)/(k*T))*v**2*dv))
def barx(v):
    return int(v/deltav)
nhisto = int(4500/deltav)
histo = []
for i in range(nhisto): histo.append(0.0)
histo[barx(pavg/m)] = N
accum = []
for i in range(int(3000/deltav)): accum.append([deltav*(i+.5),0])
vdist = gvbars(color=color.red, delta=deltav )
def interchange(v1, v2):  # remove from v1 bar, add to v2 bar
    barx1 = barx(v1)
    barx2 = barx(v2)
    if barx1 == barx2:  return
    histo[barx1] -= 1
    histo[barx2] += 1
nhisto = 0

container = box(length = 2*L, height = 2*L, width = 2*L, opacity=0.2, color = color.yellow )

# Initialize atom position and velocity
atoms = []
pos = []
p = []
for i in range(N):
    position = vector(-L_size+2*L_size*random(),-L_size+2*L_size*random(),-L_size+2*L_size*random())
    if i== N-1:
        atom = sphere(pos=position, radius = size, color=color.yellow, make_trail = True, retain = 6)
    else:
        atom = sphere(pos=position, radius = size, color=vector(random(), random(), random()))
        theta, phi = pi*random(), 2*pi*random()
    atom.m, atom.v = m, vector(vrms*sin(theta)*cos(phi), vrms*sin(theta)*sin(phi), vrms*cos(theta))
    atoms.append(atom)
    pos.append((atoms[i].pos.x,atoms[i].pos.y,atoms[i].pos.z))
    px = m*atom.v.x
    py = m*atom.v.y
    pz = m*atom.v.z
    p.append((px,py,pz))
pos = np.array(pos)
p = np.array(p)
m = np.full((N,1),m)
radius = np.full((1,N),size)
pos = pos+(p/m)*(dt/2.)
    
def vcollision(a1,a2):
    v1prime = a1.v - 2 * a2.m/(a1.m+a2.m) *(a1.pos-a2.pos)  * dot (a1.v-a2.v, a1.pos-a2.pos) / mag(a1.pos-a2.pos)**2
    v2prime = a2.v - 2 * a1.m/(a1.m+a2.m) *(a2.pos-a1.pos)  * dot (a2.v-a1.v, a2.pos-a1.pos) / mag(a2.pos-a1.pos)**2
    return v1prime, v2prime

pressure=0.
each_path = [0.] * N
avg=0.
count=0
A=0.
collision=np.zeros(N)
aa=[3.,3.]
while True:
    rate(1000)
    for i in range(len(accum)): accum[i][1] = (nhisto*accum[i][1] + histo[i])/(nhisto+1)
    if nhisto % 10 == 0:
        vdist.data = accum
    nhisto += 1
    r=pos-pos[:,np.newaxis]
    rmag = np.sqrt(np.sum(np.square(r),-1)) 
    hit = np.less_equal(rmag,radius+radius[:,None])-np.identity(N)
    hitlist = np.sort(np.nonzero(hit.flat)[0]).tolist()
    vv1=vector(0,0,0)
    vv2=vector(0,0,0)
    aa[0]=33.
    for ij in hitlist:
        i, j = divmod(ij,N)
        hitlist.remove(j*N+i) 
        v1 = atoms[i].v
        v2 = atoms[j].v
        a = mag(v2-v1)**2
        collision[i]+=1
        collision[j]+=1
        if a==0: continue
        b = 2*dot(atoms[i].pos-atoms[j].pos,v2-v1)
        c = mag(atoms[i].pos-atoms[j].pos)**2-(2*size)**2
        d = b**2-4.*a*c
        if d < 0: continue
        v1,v2=vcollision(atoms[i],atoms[j])
        interchange(mag(atoms[i].v),mag(v1))
        interchange(mag(atoms[j].v),mag(v2))
        atoms[i].v=v1
        atoms[j].v=v2
    pos=[]
    p=[]
    for i in range(N):
        a=dt*atoms[i].v
        if atoms[i].pos.x+a.x>L_size or atoms[i].pos.x+a.x<-L_size :
            atoms[i].v.x=-atoms[i].v.x
            pressure+=2*m[0]*abs(atoms[i].v.x)
        if atoms[i].pos.y+a.y>L_size or atoms[i].pos.y+a.y<-L_size:
            atoms[i].v.y=-atoms[i].v.y
            pressure+=2*m[0]*abs(atoms[i].v.y)
        if atoms[i].pos.z+a.z>L_size or atoms[i].pos.z+a.z<-L_size:
            atoms[i].v.z=-atoms[i].v.z
            pressure+=2*m[0]*abs(atoms[i].v.z)
        atoms[i].pos+=dt*atoms[i].v
        px = m*atoms[i].v.x
        py = m*atoms[i].v.y
        pz = m*atoms[i].v.z
        p.append((px,py,pz))
        pos.append((atoms[i].pos.x,atoms[i].pos.y,atoms[i].pos.z))
        
        if collision[i]==1:
            each_path[i]+=mag(dt*atoms[i].v)
            count+=1
        if collision[i]==2:
            avg+=each_path[i]
            each_path[i]=0.
            collision[i]=1
    pos = np.array(pos)
    p = np.array(p)
    t+=dt
    if t>0.5E-10:   #when 1000dt
        out=pressure/(0.5E-10*24*L**2)
        print(out)
        print(avg/count)
        path=0.
        count=0
        pressure=0.
        t=0.

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[ 108853.25606943]
3.040425109556967e-11
[ 80767.78247694]
4.785877374872321e-09
[ 80270.56938333]
8.642114179855956e-09
[ 93132.79535296]
4.4447070839671156e-08
[ 91951.02604942]


ZeroDivisionError: float division by zero